### PR TITLE
Issues/001 url layout

### LINKED ISSUE #1: Discuss url layout
* No .html?
* Include episode number?
* Is it important to have the (full) date in the url?

### PR DESCRIPTION
**Pull request by duffleit**
* Changed Jekyll permalink to just `:title`. Extended title with episode number. Thus, `/2018/08/01/solid.html` has changed to `/001-solid`.
* Added simple meta-redirect for existing post. 

Fixes #1

### CODE REVIEW

**Review by paulroho — CHANGES_REQUESTED** [review]
I think we should include the episode number in one way or another.

* /episodes/01/solid
* /01-solid

What do you think?

**Comment by duffleit** [comment]
But `/001-solid`, includes the episode number? :)

**Comment by paulroho** [comment]
But where does the episode number come from? I see just `permalink: /:title` in _config.yml. But of course, I trust you that it works as you say. :)

**Comment by duffleit** [comment]
Ah, it‘s working because the file was renamed. :)

**Pull request merged**
